function J = objJ(x,CoMPos,rCentroidSide,rCentroidBotA,rCentroidBotB,...
    rCentroidSlant,uCentroidSide,uCentroidBotA,uCentroidBotB,uCentroidSlant,...
    sideDotPosVec_cm,botADotPosVec_cm,botBDotPosVec_cm)

%OBJJ Summary of this function goes here
%   Detailed explanation goes here

% x = [roll, pitch, yaw]

% rCentroidSide = tsc.rCentroidSide.Data(:,:,end);
% rCentroidBotA = tsc.rCentroidBotA.Data(:,:,end);
% rCentroidBotB = tsc.rCentroidBotB.Data(:,:,end);
% rCentroidSlant = tsc.rCentroidSlant.Data(:,:,end);
% 
% uCentroidSide = tsc.uCentroidSide.Data(:,:,end);
% uCentroidBotA = tsc.uCentroidBotA.Data(:,:,end);
% uCentroidBotB = tsc.uCentroidBotB.Data(:,:,end);
% uCentroidSlant = tsc.uCentroidSlant.Data(:,:,end);
% 
% sideDotPosVec_cm = params.sideDotPosVec_cm.Value';
% botADotPosVec_cm = params.botADotPosVec_cm.Value';
% botBDotPosVec_cm = params.botBDotPosVec_cm.Value';

RGB = calculateRotationMatrix(x(1),x(2),x(3));
RBG = RGB';

d1 = uCentroidSide'*(CoMPos - RBG*sideDotPosVec_cm)/(uCentroidSide'*rCentroidSide);
e1 = dot( ((CoMPos + RBG*sideDotPosVec_cm) - (rCentroidSide + uCentroidSide*d1)),...
          ((CoMPos + RBG*sideDotPosVec_cm) - (rCentroidSide + uCentroidSide*d1)) );

d2 = uCentroidBotA'*(CoMPos - RBG*botADotPosVec_cm)/(uCentroidBotA'*rCentroidBotA);
e2 = dot( ((CoMPos + RBG*botADotPosVec_cm) - (rCentroidBotA + uCentroidBotA*d2)),...
          ((CoMPos + RBG*botADotPosVec_cm) - (rCentroidBotA + uCentroidBotA*d2)) );

d3 = uCentroidBotB'*(CoMPos - RBG*botBDotPosVec_cm)/(uCentroidBotB'*rCentroidBotB);
e3 = dot( ((CoMPos + RBG*botBDotPosVec_cm) - (rCentroidBotB + uCentroidBotB*d3)),...
          ((CoMPos + RBG*botBDotPosVec_cm) - (rCentroidBotB + uCentroidBotB*d3)) );

d4 = uCentroidSlant'*(CoMPos - RBG*botBDotPosVec_cm)/(uCentroidSlant'*rCentroidSlant);
e4 = dot( ((CoMPos + RBG*botBDotPosVec_cm) - (rCentroidSlant + uCentroidSlant*d4)),...
          ((CoMPos + RBG*botBDotPosVec_cm) - (rCentroidSlant + uCentroidSlant*d4)) );

J = e1 + e2 + e3 + e4;

% e1 = (x(1) + sideDotVecBF(1) - sideCamPos(1) - (1/(dot(sideCamPos,uSide)))*uSide(1)*(x(1)*uSide(1) + x(2)*uSide(2) + x(3)*uSide(3)...
%     + sideDotVecBF(1)*uSide(3)*sin(x(5)) - (sideDotVecBF(2)*cos(x(4)) - sideDotVecBF(3)*sin(x(4)))*(uSide(2)*cos(x(6)) - uSide(1)*sin(x(6)))...
%     - sin(x(5))*(sideDotVecBF(3)*cos(x(4)) + sideDotVecBF(2)*sin(x(4)))*(uSide(1)*cos(x(6)) + uSide(2)*sin(x(6)))...
%     - cos(x(5))*(sideDotVecBF(3)*uSide(3)*cos(x(4)) + sideDotVecBF(1)*uSide(1)*cos(x(6)) + sideDotVecBF(2)*uSide(3)*sin(x(4)) + sideDotVecBF(1)*uSide(2)*sin(x(6)))))^2 ...
%     + (x(2) + sideDotVecBF(2) - sideCamPos(2) - (1/(dot(sideCamPos,uSide)))*uSide(2)*(x(1)*uSide(1) + x(2)*uSide(2) + x(3)*uSide(3)...
%     + sideDotVecBF(1)*uSide(3)*sin(x(5)) - (sideDotVecBF(2)*cos(x(4)) - sideDotVecBF(3)*sin(x(4)))*(uSide(2)*cos(x(6)) - uSide(1)*sin(x(6)))...
%     - sin(x(5))*(sideDotVecBF(3)*cos(x(4)) + sideDotVecBF(2)*sin(x(4)))*(uSide(1)*cos(x(6)) + uSide(2)*sin(x(6)))...
%     - cos(x(5))*(sideDotVecBF(3)*uSide(3)*cos(x(4)) + sideDotVecBF(1)*uSide(1)*cos(x(6)) + sideDotVecBF(2)*uSide(3)*sin(x(4)) + sideDotVecBF(1)*uSide(2)*sin(x(6)))))^2 ...
%     + (x(3) + sideDotVecBF(3) - sideCamPos(3) - (1/(dot(sideCamPos,uSide)))*uSide(3)*(x(1)*uSide(1) + x(2)*uSide(2) + x(3)*uSide(3)...
%     + sideDotVecBF(1)*uSide(3)*sin(x(5)) - (sideDotVecBF(2)*cos(x(4)) - sideDotVecBF(3)*sin(x(4)))*(uSide(2)*cos(x(6)) - uSide(1)*sin(x(6)))...
%     - sin(x(5))*(sideDotVecBF(3)*cos(x(4)) + sideDotVecBF(2)*sin(x(4)))*(uSide(1)*cos(x(6)) + uSide(2)*sin(x(6)))...
%     - cos(x(5))*(sideDotVecBF(3)*uSide(3)*cos(x(4)) + sideDotVecBF(1)*uSide(1)*cos(x(6)) + sideDotVecBF(2)*uSide(3)*sin(x(4)) + sideDotVecBF(1)*uSide(2)*sin(x(6)))))^2;
% 
% e2 = (x(1) + botADotVecBF(1) - botCamPos(1) - (1/(dot(botCamPos,uBotA)))*uBotA(1)*(x(1)*uSide(1) + x(2)*uSide(2) + x(3)*uSide(3)...
%     + sideDotVecBF(1)*uSide(3)*sin(x(5)) - (sideDotVecBF(2)*cos(x(4)) - sideDotVecBF(3)*sin(x(4)))*(uSide(2)*cos(x(6)) - uSide(1)*sin(x(6)))...
%     - sin(x(5))*(sideDotVecBF(3)*cos(x(4)) + sideDotVecBF(2)*sin(x(4)))*(uSide(1)*cos(x(6)) + uSide(2)*sin(x(6)))...
%     - cos(x(5))*(sideDotVecBF(3)*uSide(3)*cos(x(4)) + sideDotVecBF(1)*uSide(1)*cos(x(6)) + sideDotVecBF(2)*uSide(3)*sin(x(4)) + sideDotVecBF(1)*uSide(2)*sin(x(6)))))^2 ...
%     + (x(2) + sideDotVecBF(2) - sideCamPos(2) - (1/(dot(sideCamPos,uSide)))*uSide(2)*(x(1)*uSide(1) + x(2)*uSide(2) + x(3)*uSide(3)...
%     + sideDotVecBF(1)*uSide(3)*sin(x(5)) - (sideDotVecBF(2)*cos(x(4)) - sideDotVecBF(3)*sin(x(4)))*(uSide(2)*cos(x(6)) - uSide(1)*sin(x(6)))...
%     - sin(x(5))*(sideDotVecBF(3)*cos(x(4)) + sideDotVecBF(2)*sin(x(4)))*(uSide(1)*cos(x(6)) + uSide(2)*sin(x(6)))...
%     - cos(x(5))*(sideDotVecBF(3)*uSide(3)*cos(x(4)) + sideDotVecBF(1)*uSide(1)*cos(x(6)) + sideDotVecBF(2)*uSide(3)*sin(x(4)) + sideDotVecBF(1)*uSide(2)*sin(x(6)))))^2 ...
%     + (x(3) + sideDotVecBF(3) - sideCamPos(3) - (1/(dot(sideCamPos,uSide)))*uSide(3)*(x(1)*uSide(1) + x(2)*uSide(2) + x(3)*uSide(3)...
%     + sideDotVecBF(1)*uSide(3)*sin(x(5)) - (sideDotVecBF(2)*cos(x(4)) - sideDotVecBF(3)*sin(x(4)))*(uSide(2)*cos(x(6)) - uSide(1)*sin(x(6)))...
%     - sin(x(5))*(sideDotVecBF(3)*cos(x(4)) + sideDotVecBF(2)*sin(x(4)))*(uSide(1)*cos(x(6)) + uSide(2)*sin(x(6)))...
%     - cos(x(5))*(sideDotVecBF(3)*uSide(3)*cos(x(4)) + sideDotVecBF(1)*uSide(1)*cos(x(6)) + sideDotVecBF(2)*uSide(3)*sin(x(4)) + sideDotVecBF(1)*uSide(2)*sin(x(6)))))^2;

end
