function R = calculateRotationMatrix(roll,pitch,yaw)
% This code calculates the rotation matrix called RGB in the Mathematica
% notebook rotationMatrix.nb located in the documentation folder.
Ryaw = [...
    cos(yaw) sin(yaw) 0;...
    -sin(yaw) cos(yaw) 0;...
    0 0 1];

Rpitch = [...
    cos(pitch) 0 -sin(pitch);...
    0 1 0;...
    sin(pitch) 0 cos(pitch)];

Rroll = [...
    1 0 0;...
    0 cos(roll) sin(roll);...
    0 -sin(roll) cos(roll)];

R = Rroll*Rpitch*Ryaw;


