maskObj = Simulink.Mask.get(gcb);
% tabContObj = maskObj.getDialogControl('tabContainer');
for ii = 1:5
    tabName = sprintf('cam%dTab',ii);
    
    maskObj.addParameter('Type','edit',...
        'Prompt','Camera position vector (cm)',...
        'Name',sprintf('cam%dPosVec',ii),...
        'Value','[0 0 1]',...
        'Container',tabName);
    
    maskObj.addParameter('Type','edit',...
        'Prompt','Camera Euler angles (deg)',...
        'Name',sprintf('cam%dEulAng',ii),...
        'Value','[0 0 0]',...
        'Container',tabName);
    
    maskObj.addParameter('Type','edit',...
        'Prompt','Distance 2 glass (cm)',...
        'Name',sprintf('cam%dDist2Glass',ii),...
        'Value','1',...
        'Container',tabName);
    
    maskObj.addParameter('Type','edit',...
        'Prompt','Indices of refraction',...
        'Name',sprintf('cam%dIdxRef',ii),...
        'Value','[1 1 1]',...
        'Container',tabName);
    
    maskObj.addParameter('Type','edit',...
        'Prompt','Glass out normal vector',...
        'Name',sprintf('cam%dNormVec',ii),...
        'Value','[0 0 1]',...
        'Container',tabName);
    
    maskObj.addParameter('Type','edit',...
        'Prompt','Glass thickness (cm)',...
        'Name',sprintf('cam%dGlassThick',ii),...
        'Value','1',...
        'Container',tabName);
    
    maskObj.addParameter('Type','edit',...
        'Prompt','Image dimensions (px) [numRows numCols]',...
        'Name',sprintf('cam%dImgDims',ii),...
        'Value','[1000 2000]',...
        'Container',tabName);
    
    maskObj.addParameter('Type','edit',...
        'Prompt','Camera field of view angles (deg) [horiz vert]',...
        'Name',sprintf('cam%dFoVAngs',ii),...
        'Value','[30 30]',...
        'Container',tabName);
        
    maskObj.addParameter('Type','edit',...
        'Prompt','Number of dots tracked',...
        'Name',sprintf('cam%dNumDots',ii),...
        'Value','2',...
        'Container',tabName);
   
end