close all

timeIndex = length(tsc.CoMPosVec_cm.Time);
rayLength = 50;

cameraPosVecs   = {'sideCamPosVec_cm','botCamPosVec_cm','slntCamPosVec_cm'};
unitVecNames    = {'uCentroidSide','uCentroidBotA','uCentroidBotB','uCentroidSlant'};
rayBaseVecNames = {'rCentroidSide','rCentroidBotA','rCentroidBotB','rCentroidSlant'};
dotPosVecNames  = {'sideDotPos_cm','botADotPos_cm','botBDotPos_cm'};
figure
set(gca,'NextPlot','add')
for ii = 1:length(unitVecNames)
    scatter3(...
       tsc.(rayBaseVecNames{ii}).Data(1,:,timeIndex),...
       tsc.(rayBaseVecNames{ii}).Data(2,:,timeIndex),...
       tsc.(rayBaseVecNames{ii}).Data(3,:,timeIndex),...
       'Marker','o','CData',[0 0 1]);
   plot3(...
       [tsc.(rayBaseVecNames{ii}).Data(1,:,timeIndex) tsc.(rayBaseVecNames{ii}).Data(1,:,timeIndex)+rayLength*tsc.(unitVecNames{ii}).Data(1,:,timeIndex)],...
       [tsc.(rayBaseVecNames{ii}).Data(2,:,timeIndex) tsc.(rayBaseVecNames{ii}).Data(2,:,timeIndex)+rayLength*tsc.(unitVecNames{ii}).Data(2,:,timeIndex)],...
       [tsc.(rayBaseVecNames{ii}).Data(3,:,timeIndex) tsc.(rayBaseVecNames{ii}).Data(3,:,timeIndex)+rayLength*tsc.(unitVecNames{ii}).Data(3,:,timeIndex)],...
       'LineStyle','--','LineWidth',1,'Color','k');
end

for ii = 1:length(cameraPosVecs)
    scatter3(...
       params.(cameraPosVecs{ii}).Value(1),...
       params.(cameraPosVecs{ii}).Value(2),...
       params.(cameraPosVecs{ii}).Value(3),...
       'Marker','o','CData',[0 0 0]);
end
CoMPosVec = tsc.CoMPosVec_cm.Data(:,:,end);
scatter3(...
        CoMPosVec(1),...
        CoMPosVec(2),...
        CoMPosVec(3),...
        'Marker','x','CData',[0 0 1]);
    
for ii = 1:length(dotPosVecNames)
    scatter3(...
        tsc.(dotPosVecNames{ii}).Data(1,:,timeIndex),...
        tsc.(dotPosVecNames{ii}).Data(2,:,timeIndex),...
        tsc.(dotPosVecNames{ii}).Data(3,:,timeIndex),...
        'Marker','o','CData',[0 0 1]);
    plot3(...
        [CoMPosVec(1) tsc.(dotPosVecNames{ii}).Data(1,:,timeIndex)],...
        [CoMPosVec(2) tsc.(dotPosVecNames{ii}).Data(2,:,timeIndex)],...
        [CoMPosVec(3) tsc.(dotPosVecNames{ii}).Data(3,:,timeIndex)],...
       'LineStyle','--','LineWidth',1,'Color','r');
end

scatter3(0,0,0,'Marker','o','CData',[1 0 0])
set(gcf,'Position',1e3*[1.9210   -0.1750    1.9200    0.9648])
view([-123.1018 24.7266])

grid on
axis equal
axis square