function R = eul2Rot(eulAng)
% eulAng = [roll pitch yaw] in rad describes orientation of B with respect
% to A.  Function returns the rotation matrix A^[c]^B, ie, for a vector, v,
% represented in B as v_B and in A as v_A, v_A = (A^[c]^B)*v_B.
% Note that the columns of A^[c]^B are the unit vectors of B, represented
% in A.

Rx = [...
    1   0                0;...
    0   cos(eulAng(1))  -sin(eulAng(1));...
    0   sin(eulAng(1))   cos(eulAng(1))];

Ry = [...
    cos(eulAng(2))  0   sin(eulAng(2));...
    0               1   0;...
    -sin(eulAng(2)) 0   cos(eulAng(2))];

Rz = [...
    cos(eulAng(3))  -sin(eulAng(3))  0;...
    sin(eulAng(3))   cos(eulAng(3))  0;...
    0                0               1];

R = Rx*Ry*Rz;
end